### ISSUE TITLE
keebkaigi でググるとDaihukuさんの画像をGoogleが拾っているっぽい

### ISSUE THREAD

**Issue by kakutani** [keebkaigi/keebkaigi.github.io#27]
なにをどうすればいいのかサッパリですが、こうなっちゃいます(と、Asakusa.rbで教えてもらった):

![image](https://user-images.githubusercontent.com/2160/229820917-73eb35bf-c14d-4732-bc65-2f50c075d45e.png)

Daihukuさんがいやだ、というわけじゃないですw (念の為)。

**Comment by taea** [comment]
多分、ページの中で最初に img src で呼んでる画像を拾っちゃうんですね（ロゴは背景画像にしちゃっているんですよね）
こちらもなんとかしたいと思います 🙏 🍓

**Comment by kakutani** [comment]
> こちらもなんとかしたいと思います 🙏 🍓

ぜんぜん急ぎませんが、アーカイブの観点からは対応いただけると助かります! ｲﾝﾀｰﾈｯﾂに残る仕事!

**Comment by swanmatch** [comment]
そいやこの問題ってResolveしてますかね？
![image](https://user-images.githubusercontent.com/6962187/231926799-1a68b258-70ef-458c-9b3a-27e24d7b1d22.png)

**Comment by kakutani** [comment]
すばらしい〜。「もしかして: keeb 会議」はGoogleさんもうちょっと勉強してほしいですね…
